cd event-bus
mvn -Pf8-local-deploy
cd ../laboratoire
mvn -Pf8-local-deploy
cd ../imagerie
mvn -Pf8-local-deploy
cd ../uds-chirabdo
mvn -Pf8-local-deploy
cd ../administration
mvn -Pf8-local-deploy
cd ../api-gateway
mvn -Pf8-local-deploy
