cd event-bus
mvn fabric8:deploy
cd ../laboratoire
mvn fabric8:deploy
cd ../imagerie
mvn fabric8:deploy
cd ../uds-chirabdo
mvn fabric8:deploy
cd ../administration
mvn fabric8:deploy
cd ../api-gateway
mvn fabric8:deploy
cd ../uds-chirortho
mvn fabric8:deploy
